### ISSUE TITLE
This project is unlicensed

### ISSUE THREAD

**Issue by ex-nerd** [jtblin/aws-mock-metadata#1]
I would like to use/fork/contribute to this project but it is currently unlicensed, which in most countries means that the license is a default "all rights reserved" copyright (preventing anyone from using your code).

Please see github documentation/recommendations and choose a license:

https://help.github.com/articles/open-source-licensing/
http://choosealicense.com/

My personal favorites these days are the MIT (same as the python implementation that inspired this project) or Modified BSD licenses.

**Comment by jtblin** [comment]
Thanks for pointing out. I usually use BSD everywhere so I've added it here too now.
