### ISSUE TITLE
Test Coverage

### ISSUE THREAD

**Issue by CpuID** [jtblin/aws-mock-metadata#9]
Hey @jtblin 

I currently have a fork at https://github.com/CpuID/aws-mock-metadata with about 80~% test coverage over the entire EC2 Metadata API (including redirects, endpoint listings, etc), which is close to all passing but still needs some minor work.

Would you be interested in adding me as a maintainer to the project? Happy to PR my changes back here in the process also. Or would you prefer me to maintain an independent fork?

Thanks.

**Comment by CpuID** [comment]
The test coverage in my branch that does exist now passes :) Still could use extra endpoints to fill in a few blanks, but it's almost a complete mock now.

**Comment by jtblin** [comment]
hey @CpuID, sounds awesome! Added you as a collaborator so that you can add merge your fork into this. You should have received an invite. Thanks!

**Comment by CpuID** [comment]
Thanks :)

**Comment by CpuID** [comment]
This was mostly ticked off in https://github.com/jtblin/aws-mock-metadata/pull/10 - some fails still though? Needs checking

**Comment by CpuID** [comment]
Fixed failing tests, calling this close enough for now 76~%.
